#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Simple wiki with command line interface and git support for storing
# personal notes

# Read the configuration file if it exists
[ -z "$MYWIKI_CONFIG" ] && MYWIKI_CONFIG=~/.mywiki.config/
[ -f "$MYWIKI_CONFIG" ] && . $MYWIKI_CONFIG

# Set the default configuration
[ -z "$DATA_DIR" ]	&& DATA_DIR=~/.mywiki/
[ -z "$HEAD_LINES" ]	&& HEAD_LINES=2
[ -z "$TEMPLATE_FILE" ]	&& TEMPLATE_FILE=${DATA_DIR}/.template
[ -z "$HIDDEN_TAG" ] && HIDDEN_TAG="--- HIDDEN ---"

create_template()
{
cat << EOF
TAGS:
DESCRIPTION:
EOF
}

error()
{
	echo "ERROR: ${1}"
	exit 1
}

error_usage()
{
	echo "Error: ${1}!"
	usage
	exit 1
}

usage()
{
	echo "$(basename $0) [new | edit | list | rm | <search terms> ]
	new <filename>		- create a new wiki file
	edit <filename>		- edit a wiki file
	rm <filename>		- remove a wiki file
	list			- list all wiki files
	append <filename>	- append line to the file
	show <filename>		- cat the filename
	<search terms>		- search for specified terms"
}

header()
{
	COLUMNS=$(tput cols)
	eval printf -- '-%.s' {1..$COLUMNS}
	echo
	title=$1
	tput bold
	printf "%*s\n" $(((${#title}+$COLUMNS)/2)) "$title"
	tput sgr0
	eval printf -- '-%.s' {1..$COLUMNS}
	echo
}

git_pull()
{
	[ ! -d "$DATA_DIR/.git" ] && return
	(
	cd $DATA_DIR
	git pull
	)
}

git_add()
{
	[ ! -d "$DATA_DIR/.git" ] && return
	(
		cd $DATA_DIR
		[ -z "$1" ] && error "git: File to add to git repository was not specified"
		if [ ! -f "$1" ]; then
			# Check if the file was deleted from repository
			git ls-files -d | grep -E "^${1}$" 2> /dev/null
			[ $? -ne 0 ] && error "git: File \"$1\" does not exist"
			op="Delete file"
		else
			# Check if the file already exists in the repository
			op="Add new file"
			git ls-files | grep -E "^${1}$" 2> /dev/null
			[ $? -eq 0 ] && op="Update file"

		fi

		git add $1
		changes=`git --no-pager diff --cached | wc -l`
		# If there are no changes, no need to commit
		[ "$changes" == "0" ] && return
		git commit -m "$op $1"
	)
}

git_push()
{
	[ ! -d "$DATA_DIR/.git" ] && return
	(
	cd $DATA_DIR
	git push
	)
}

new()
{
	if [ $# -ne 2 ]; then
		error_usage "filename should be provided"
	fi
	filename=$2
	if [ -f ${DATA_DIR}/$filename ]; then
		echo "File \"$filename\" already exist!"
		exit 1
	fi
	echo "Creating new wiki entry \"$filename\""

	case "$(basename $EDITOR)" in
	vim)
		( $EDITOR -c "read $TEMPLATE_FILE" ${DATA_DIR}/$filename )
		;;
	*)
		cat $TEMPLATE_FILE > ${DATA_DIR}/$filename
		( $EDITOR ${DATA_DIR}/$filename )
	esac

	if [ -f ${DATA_DIR}/$filename ]; then
		echo "New entry \"$filename\" was successfully created!"
		cat ${DATA_DIR}/$filename
		git_add $filename
	else
		echo "New entry \"$filename\" was NOT created!"
	fi
}

list()
{
	if [ $# -gt 1 ]; then
		error_usage "unexpected arguments"
	fi
	for file in $(ls $DATA_DIR); do
		header $file
		head -n${HEAD_LINES} ${DATA_DIR}/$file | sed -e "s/\(.*\)/\t\1/"
	done
}

remove()
{
	if [ $# -ne 2 ]; then
		error_usage "filename should be provided"
	fi
	filename=$2
	if [ -f ${DATA_DIR}/$filename ]; then
		echo "Removing \"$filename\"!"
		rm ${DATA_DIR}/$filename
		git_add $filename
	else
		echo "\"$filename\" entry does NOT exist!"
		exit 1
	fi
}

edit()
{
	if [ $# -ne 2 ]; then
		error_usage "filename should be provided"
	fi
	filename=$2
	if [ -f ${DATA_DIR}/$filename ]; then
		( $EDITOR ${DATA_DIR}/$filename )
		git_add $filename
	else
		echo "\"$filename\" entry does NOT exist!"
		exit 1
	fi
}

do_append()
{
	if [ $# -lt 2 ]; then
		error_usage "filename should be provided"
	fi
	filename=$2
	shift 2

	if [ ! -f ${DATA_DIR}/$filename ]; then
		cp $TEMPLATE_FILE ${DATA_DIR}/$filename
	fi

	echo $@ >> ${DATA_DIR}/$filename
	git_add $filename
}

do_show()
{
	shift
	hidden=0
	if [ "$1" == "-h" ]; then
		hidden=1
		shift
	fi
	if [ $# -ne 1 ]; then
		error_usage "too many arguments"
	fi
	filename=$1
	if [ ! -f ${DATA_DIR}/$filename ]; then
		echo "\"$filename\" does not exist!"
		exit 1
	fi
	if [ $hidden -eq 0 ]; then
		cat ${DATA_DIR}/$filename
	else
		sed "1,/${HIDDEN_TAG}/d" ${DATA_DIR}/$filename
	fi
}

search()
{
	if [ $# -lt 1 ]; then
		error_usage "search words should be provided"
	fi
	string=`echo $@ | sed -e "s/ / -e /g"`
	echo "Searching for terms: $string"
	found=0
	for file in $(ls $DATA_DIR); do
		if [ "$file" != "$string" ]; then
			head -n1 ${DATA_DIR}/$file | grep -i -q -e $string
			[ $? -ne 0 ] && continue
		fi
		header $file
		sed "s/\(.*\)/\t\1/;/${HIDDEN_TAG}/Q" ${DATA_DIR}/$file
		found=$(($found+1))
	done
	if [ $found -eq 0 ]; then
		echo "Nothing was found!"
	fi
}

# Create the DATA_DIR if it does not exist yet
if [ ! -d $DATA_DIR ]; then
	mkdir $DATA_DIR 2>&1> /dev/null || error "Can not create $DATA_DIR"
fi

git_pull

# Create the template if it does not exist yet
if [ ! -f $TEMPLATE_FILE ]; then
	create_template > $TEMPLATE_FILE
fi

# Run the required command
CMD=$1
case $CMD in
	new | add)	new $@;;
	edit)		edit $@;;
	list)		list $@;;
	append)		do_append $@;;
	show|cat)	do_show $@;;
	rm | remove)	remove $@;;
esac

# After some command we need to push changes to git repository
case $CMD in
	new|edit|rm|remove|add|append)
		git_push
		exit 0;;
	list|show|cat)
		exit 0;;
esac

if [ $# -lt 1 ]; then
	list
else
	search $@
fi

exit 0
